export default function About() {
  return (
    <article>
      <header className="border-b">Southern Code Technical Test</header>
      <hr></hr>
      <h2 className="font-bold shadow-sm">About Next13</h2>
      <p>
        Took the chance to try Next13 and found it amazing, compared to previous
        version I found really interesting the automatic error boundaries and
        loading through name conventions. Another amazing change that I think
        will def change the game is that every component is server-client by
        default.
        <br />
        Overall I found the framework amazing and with lots of potentials but
        still a little buggy and betaish.
      </p>
      <h2  className="font-bold shadow-sm">Making the space.</h2>
      <p>
        The space component is autogenerated in the server side but if SEO would
        be major thing for the project it can always be generated in the client
        avoiding to generate non semantic HTML. It would be possible to generate
        only on styles but this aproach gives the chance for extra effects if
        the looks are the priority.
        <br />
        Honestly I really like making little effects and small movements around
        the page, I think makes the page a lot more appealing and enjoyable.
      </p>
      <h2  className="font-bold shadow-sm">NASA API</h2>
      <p>
        Not going to lie, this API could be way better documentated, had to
        check de repository to figure out endpoints to make all the data loading
        dinamically.
      </p>
      <h2  className="font-bold shadow-sm">Pagination</h2>
      <p>
        Made infinite scroll pagination except on latest pics from Curiosity, as
        the first pictures are being fetched on the server side by Next and the
        htmls is served I made it all in one go.
      </p>
      <h2  className="font-bold shadow-sm">Some Autocritics</h2>
      <p>
        Refactor always could be better. I could had more heavy relied on the granularity
        of React components.
      </p>
      <p>Some types could be a lot more accurate.</p>
      <p>Context Api not working.</p>
      <p>No tests.</p>
      <p>This about page could be nicer looking.</p>
    </article>
  );
}
